Feature/kan 24 auth token endpoint
RezaBG/TUDU pull request #29
Opened 2024-11-30 20:53 UTC by RezaBG

**Implement Authentication Endpoint and Refactor User/Task Management**

1. User Management Updates:

- Improved user creation and update processes with enhanced validation.
- Ensured username and email uniqueness during updates.
- Added error handling for invalid user data.

2. Task Management Enhancements:

- Added robust endpoints for creating, updating, and deleting tasks.
- Enhanced validation for task ownership and data integrity.

3. Model Refactoring:

- Updated User and Task models using Mapped types for clarity and better type enforcement.
- Improved relationships between models for maintainability.

4. Testing and Repository Cleanup:

- Updated tests for new endpoints and refactored models.
- Performed repository optimization (git gc and git prune).

2024-12-02 08:05 UTC, IshanRastogi requested changes

2024-12-02 08:05 UTC, IshanRastogi commented on README.md
> +   git checkout -b feature/your-feature-name
```git checkout -b feature/your-feature-name``` can be replaced by the newer command: 
```git branch feature/your-feature-name```

2024-12-02 08:05 UTC, IshanRastogi commented on alembic/versions/09b5599b6005_add_status_field_to_task_model.py
> +    op.add_column('tasks', sa.Column('status', sa.String(), nullable=True))
can you try to have the `type` of the `status` column as the `status_enum` that you've defined in the next file instead of just a `string` ?

2024-12-02 08:05 UTC, IshanRastogi commented on src/routers/auth.py
> +def get_user_by_username(db: Session, username: str):
do you want to update this method to filter only on `active` users ? 
I'm assuming that's the functionality you had in mind when you created the `disabled` flag  in the table.

2024-12-02 12:09 UTC, RezaBG commented on alembic/versions/09b5599b6005_add_status_field_to_task_model.py
> +    op.add_column('tasks', sa.Column('status', sa.String(), nullable=True))
I added the status column with the taskstatus enum type ('pending', 'in-progress', 'completed'). The column is nullable due to migration constraints. Currently, there’s a mismatch between the database enum values (PENDING, IN_PROGRESS, COMPLETED) and the lowercase values (pending, in-progress, completed) being passed, causing test failures. I’ll align these values to fix the issue.

2024-12-02 12:22 UTC, RezaBG commented on src/routers/auth.py
> +def get_user_by_username(db: Session, username: str):
I’ve updated the function to only retrieve users where disabled == False, ensuring it filters for active users, as you suggested

2024-12-05 09:37 UTC, IshanRastogi submitted a review, later dismissed

2024-12-05 11:34 UTC, IshanRastogi submitted a review, later dismissed

2024-12-05 11:34 UTC, IshanRastogi approved these changes

2024-12-05 14:28 UTC, IshanRastogi approved these changes

2024-12-05 14:29 UTC, merged